---
- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3
      - docker.io
      - python3-docker

- name: Upgrade packages
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: Set docker to start on boot
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Start docker
  command: echo "starting docker"
  notify: "start docker"
